import "@radix-ui/themes/styles.css";
import './theme-config.css'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Inter} from "next/font/google";
import "./globals.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import Navbar from "./Navbar";


const inter = Inter({
  subsets: ['latin'],
  variable: '--fontinter'
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.variable}
      >
        <Theme accentColor="orange" grayColor="slate" radius="large"></Theme>
        <Theme>
        <Navbar />
        <main className="p-5">{children}</main>
        <ThemePanel />
      </Theme>
      </body>
    </html>
  );
}
